version: '3.3'

services:
  server:
    image: promnesia
    build:
      context: ./
      dockerfile: docker/Dockerfile
    # Uncomment to enable persisent volumes
    volumes:
      - ./data:/data
    ports:
      - "13131:13131"
    restart: always
  indexer:
    image: promnesia-indexer
    build:
      context: ./
      dockerfile: docker/Dockerfile-indexer
    # Uncomment to enable persisent volumes
    # create config.py inside ./data
    #volumes:
    #  - ./data:/data
    environment:
      CRONTAB: "* * * * * cd /usr/src/promnesia && python -m promnesia index --config /data/config.py"
