version: '3.3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    # Uncomment to enable persisent volumes
    #volumes:
    #  - ./data:/data
    ports:
      - "13131:13131"
    restart: always
  indexer:
    container_name: indexer
    build:
      context: ./
      dockerfile: Dockerfile
    # Uncomment to enable persisent volumes
    # create config.py inside ./data
    #volumes:
    #  - ./data:/data
    command: ["python", "-m", "promnesia", "index", "--config", "/data/config.py"]
